---
# group vars for cluster manager
splunk_app_deploy_path: etc/master-apps # default subdirectory in splunk_home that apps from git should be installed to, overridable in git_apps if you want to install to etc/apps
git_server: https://github.com/
git_key: ~/.ssh/id_rsa.pub
git_project: G20100
git_apps:
    - name: 001_index

