---
# YAML format inventory with nested groups for variable inheritance
# Mason Morales, Splunk, Inc.
# References:
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# Read this: https://docs.ansible.com/ansible/2.9/plugins/inventory/yaml.html
# https://www.digitalocean.com/community/tutorials/how-to-manage-multistage-environments-with-ansible
# ##########################################################################
all:
  children:

    full:
      children:

        licensemaster:
          hosts: 
           i-0490b8c75633fcd82.ec2.splunkit.io:

        deploymentserver:
          hosts:
#            i-0db02a63a12ff83f1.ec2.splunkit.io:
        dmc:
          hosts:
#            i-0db02a63a12ff83f1.ec2.splunkit.io:
 
        shdeployer:
          hosts: 
            i-07179d4d2e1e695d1.ec2.splunkit.io:
          vars:
            target_shc_group_name: shc01

        search:
          children:
            shc:
              hosts:
                i-0eaed08c273c2fdfe.ec2.splunkit.io:
                i-002713433f1e01e5d.ec2.splunkit.io:
                i-025b7b80e593fc2a2.ec2.splunkit.io:


        clustermanager:
          hosts:
            i-078f5ebdb904039c4.ec2.splunkit.io:
        
        indexers:
          hosts:
            i-0afe9c24b38deb46b.ec2.splunkit.io:
            i-0c88eff4f2f36be69.ec2.splunkit.io:
            i-0fc0408a20e3ec59a.ec2.splunkit.io:


        heavyforwarder:
          hosts:

        standalone:
            hosts:
#              i-0490b8c75633fcd82.ec2.splunkit.io:
